/**
 * Extend React data with remaining 10 topics
 */
const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'js', 'data', 'react-data.js');

const topics = [
{
    id: "render-props", title: "Render Props & Patterns", icon: "bi-braces",
    questions: [
        { q: "What is the render props pattern?", a: "<p>Render props is a technique where a component receives a function as a prop and calls it to determine what to render, enabling code sharing between components.</p><pre><code>function MouseTracker({ render }) {\n  const [pos, setPos] = useState({ x: 0, y: 0 });\n  return (\n    &lt;div onMouseMove={e =&gt; setPos({ x: e.clientX, y: e.clientY })}&gt;\n      {render(pos)}\n    &lt;/div&gt;\n  );\n}\n\n&lt;MouseTracker render={({ x, y }) =&gt; &lt;p&gt;Mouse: {x}, {y}&lt;/p&gt;} /&gt;</code></pre>" },
        { q: "What is the children as a function pattern?", a: "<p>Instead of a named render prop, you can use <code>children</code> as a function:</p><pre><code>&lt;DataFetcher url=\"/api/users\"&gt;\n  {({ data, loading }) =&gt; loading ? &lt;Spinner /&gt; : &lt;UserList users={data} /&gt;}\n&lt;/DataFetcher&gt;</code></pre>" },
        { q: "What is the compound component pattern?", a: "<p>Compound components share implicit state through React Context, letting related components work together:</p><pre><code>function Tabs({ children }) {\n  const [active, setActive] = useState(0);\n  return (\n    &lt;TabsContext.Provider value={{ active, setActive }}&gt;\n      {children}\n    &lt;/TabsContext.Provider&gt;\n  );\n}\n\n&lt;Tabs&gt;\n  &lt;TabList&gt;&lt;Tab&gt;One&lt;/Tab&gt;&lt;Tab&gt;Two&lt;/Tab&gt;&lt;/TabList&gt;\n  &lt;TabPanels&gt;&lt;Panel&gt;Content 1&lt;/Panel&gt;&lt;Panel&gt;Content 2&lt;/Panel&gt;&lt;/TabPanels&gt;\n&lt;/Tabs&gt;</code></pre>" },
        { q: "What is the container/presentational pattern?", a: "<p>Separates business logic (containers) from UI rendering (presentational). Containers fetch data and handle state; presentational components just render UI from props.</p>" },
        { q: "What is the provider pattern?", a: "<p>Uses React Context to provide data to deeply nested components without prop drilling. Often combined with custom hooks for cleaner API.</p><pre><code>const ThemeContext = createContext();\n\nfunction ThemeProvider({ children }) {\n  const [theme, setTheme] = useState('light');\n  return (\n    &lt;ThemeContext.Provider value={{ theme, setTheme }}&gt;\n      {children}\n    &lt;/ThemeContext.Provider&gt;\n  );\n}\n\nconst useTheme = () =&gt; useContext(ThemeContext);</code></pre>" },
        { q: "What are controlled vs uncontrolled components?", a: "<p><strong>Controlled:</strong> React state controls the value. <strong>Uncontrolled:</strong> DOM controls the value, accessed via refs. Controlled components give you more control over form behavior and validation.</p>" },
        { q: "What is the observer pattern in React?", a: "<p>Components subscribe to an external store and re-render when data changes. Libraries like MobX and Zustand use this. React state management tools implement publish-subscribe patterns.</p>" },
        { q: "What is composition over inheritance in React?", a: "<p>React favors composition (nesting components, passing props, using children) over class inheritance. Components should be composed together rather than extended.</p>" },
        { q: "What is the state reducer pattern?", a: "<p>Allow consumers to control how the internal state changes by accepting a custom reducer:</p><pre><code>function useToggle({ reducer = (state, action) =&gt; action } = {}) {\n  const [on, dispatch] = useReducer(reducer, false);\n  const toggle = () =&gt; dispatch({ type: 'toggle' });\n  return { on, toggle };\n}</code></pre>" },
        { q: "What is the layout component pattern?", a: "<p>Layout components handle common page structure (header, sidebar, footer) and render children in the main content area:</p><pre><code>function DashboardLayout({ children }) {\n  return (\n    &lt;div className=\"dashboard\"&gt;\n      &lt;Sidebar /&gt;\n      &lt;main&gt;{children}&lt;/main&gt;\n      &lt;Footer /&gt;\n    &lt;/div&gt;\n  );\n}</code></pre>" }
    ]
},
{
    id: "error-boundaries", title: "Error Boundaries", icon: "bi-exclamation-triangle",
    questions: [
        { q: "What is an error boundary?", a: "<p>Error boundaries are React components that catch JavaScript errors in their child component tree, log those errors, and display a fallback UI instead of crashing the whole app.</p><pre><code>class ErrorBoundary extends React.Component {\n  state = { hasError: false };\n  static getDerivedStateFromError(error) { return { hasError: true }; }\n  componentDidCatch(error, info) { logError(error, info); }\n  render() {\n    if (this.state.hasError) return &lt;h1&gt;Something went wrong.&lt;/h1&gt;;\n    return this.props.children;\n  }\n}</code></pre>" },
        { q: "Can you create error boundaries with hooks?", a: "<p>No, error boundaries can only be class components because there are no hook equivalents for <code>getDerivedStateFromError</code> and <code>componentDidCatch</code>. However, packages like <code>react-error-boundary</code> provide a convenient wrapper.</p>" },
        { q: "What errors do error boundaries NOT catch?", a: "<ul><li>Event handlers (use try/catch instead)</li><li>Asynchronous code (setTimeout, fetch callbacks)</li><li>Server-side rendering</li><li>Errors thrown in the error boundary itself</li></ul>" },
        { q: "How do you use react-error-boundary library?", a: "<pre><code>import { ErrorBoundary } from 'react-error-boundary';\n\nfunction Fallback({ error, resetErrorBoundary }) {\n  return (\n    &lt;div role=\"alert\"&gt;\n      &lt;p&gt;Error: {error.message}&lt;/p&gt;\n      &lt;button onClick={resetErrorBoundary}&gt;Retry&lt;/button&gt;\n    &lt;/div&gt;\n  );\n}\n\n&lt;ErrorBoundary FallbackComponent={Fallback}&gt;\n  &lt;MyComponent /&gt;\n&lt;/ErrorBoundary&gt;</code></pre>" },
        { q: "What is getDerivedStateFromError?", a: "<p>A static lifecycle method called after a descendant throws an error. It receives the error and returns state updates to render a fallback UI.</p>" },
        { q: "What is componentDidCatch?", a: "<p>Called after an error has been thrown by a descendant. Receives the error and an info object with <code>componentStack</code>. Used for logging errors to a service.</p>" },
        { q: "Where should you place error boundaries?", a: "<p>Place them at strategic points: around the whole app (catch-all), around route components, around feature sections, or around any component likely to fail. Granular boundaries prevent the entire UI from breaking.</p>" },
        { q: "How do you recover from errors?", a: "<p>Use a reset mechanism (key change or reset function) to remount the failed component:</p><pre><code>&lt;ErrorBoundary key={resetKey} FallbackComponent={Fallback}&gt;\n  &lt;FailingComponent /&gt;\n&lt;/ErrorBoundary&gt;</code></pre>" },
        { q: "How do you handle errors in event handlers?", a: "<p>Error boundaries don't catch event handler errors. Use try-catch and state:</p><pre><code>function MyButton() {\n  const [error, setError] = useState(null);\n  const handleClick = () =&gt; {\n    try { riskyOperation(); }\n    catch (e) { setError(e); }\n  };\n  if (error) return &lt;p&gt;Error: {error.message}&lt;/p&gt;;\n  return &lt;button onClick={handleClick}&gt;Click&lt;/button&gt;;\n}</code></pre>" },
        { q: "What is the difference between error boundaries and try-catch?", a: "<p>Error boundaries catch errors in the React render cycle (rendering, lifecycle methods, constructors). Try-catch catches errors in imperative code (event handlers, async functions, callbacks). Both are needed for complete error handling.</p>" }
    ]
},
{
    id: "refs-useref", title: "Refs & useRef", icon: "bi-cursor",
    questions: [
        { q: "What is useRef and when to use it?", a: "<p><code>useRef</code> returns a mutable ref object with a <code>.current</code> property that persists across re-renders without causing re-renders when changed.</p><pre><code>const inputRef = useRef(null);\nconst handleFocus = () =&gt; inputRef.current.focus();\nreturn &lt;input ref={inputRef} /&gt;;</code></pre>" },
        { q: "What is the difference between useRef and useState?", a: "<p><code>useState</code> triggers re-render when value changes. <code>useRef</code> does NOT trigger re-render. Use useRef for values that need to persist without affecting the UI (timers, previous values, DOM references).</p>" },
        { q: "How do you access a DOM element with refs?", a: "<pre><code>function TextInput() {\n  const inputRef = useRef(null);\n  return (\n    &lt;&gt;\n      &lt;input ref={inputRef} /&gt;\n      &lt;button onClick={() =&gt; inputRef.current.focus()}&gt;Focus&lt;/button&gt;\n    &lt;/&gt;\n  );\n}</code></pre>" },
        { q: "What is forwardRef?", a: "<p><code>forwardRef</code> passes a ref through a component to a child DOM element:</p><pre><code>const FancyInput = forwardRef((props, ref) =&gt; (\n  &lt;input ref={ref} className=\"fancy\" {...props} /&gt;\n));\n\n// Parent\nconst ref = useRef(null);\n&lt;FancyInput ref={ref} /&gt;</code></pre>" },
        { q: "What is useImperativeHandle?", a: "<p><code>useImperativeHandle</code> customizes what ref exposes to parent components:</p><pre><code>const FancyInput = forwardRef((props, ref) =&gt; {\n  const inputRef = useRef();\n  useImperativeHandle(ref, () =&gt; ({\n    focus: () =&gt; inputRef.current.focus(),\n    clear: () =&gt; { inputRef.current.value = ''; }\n  }));\n  return &lt;input ref={inputRef} /&gt;;\n});</code></pre>" },
        { q: "How do you store previous values with useRef?", a: "<pre><code>function usePrevious(value) {\n  const ref = useRef();\n  useEffect(() =&gt; { ref.current = value; });\n  return ref.current;\n}\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n  const prevCount = usePrevious(count);\n  return &lt;p&gt;Now: {count}, Before: {prevCount}&lt;/p&gt;;\n}</code></pre>" },
        { q: "What are callback refs?", a: "<p>Callback refs receive the DOM element directly as a function argument:</p><pre><code>function MeasureNode() {\n  const [height, setHeight] = useState(0);\n  const measuredRef = useCallback(node =&gt; {\n    if (node) setHeight(node.getBoundingClientRect().height);\n  }, []);\n  return &lt;div ref={measuredRef}&gt;Height: {height}&lt;/div&gt;;\n}</code></pre>" },
        { q: "Can you use multiple refs on one element?", a: "<p>Not directly, but you can use a callback ref that assigns to multiple refs:</p><pre><code>function mergeRefs(...refs) {\n  return (node) =&gt; {\n    refs.forEach(ref =&gt; {\n      if (typeof ref === 'function') ref(node);\n      else if (ref) ref.current = node;\n    });\n  };\n}</code></pre>" },
        { q: "How do you use refs with timers?", a: "<pre><code>function Timer() {\n  const intervalRef = useRef(null);\n  useEffect(() =&gt; {\n    intervalRef.current = setInterval(() =&gt; console.log('tick'), 1000);\n    return () =&gt; clearInterval(intervalRef.current);\n  }, []);\n  const stop = () =&gt; clearInterval(intervalRef.current);\n  return &lt;button onClick={stop}&gt;Stop&lt;/button&gt;;\n}</code></pre>" },
        { q: "When should you NOT use refs?", a: "<p>Avoid refs for things that can be done declaratively. Don't use refs to: conditionally render elements (use state), update text content (use state), manage form values in most cases (use controlled components). Refs are an escape hatch for imperative DOM manipulation.</p>" }
    ]
},
{
    id: "portals", title: "Portals", icon: "bi-door-open",
    questions: [
        { q: "What are React Portals?", a: "<p>Portals render children into a DOM node outside the parent component's DOM hierarchy, while keeping them inside the React component tree for events and context.</p><pre><code>import { createPortal } from 'react-dom';\n\nfunction Modal({ children }) {\n  return createPortal(\n    &lt;div className=\"modal\"&gt;{children}&lt;/div&gt;,\n    document.getElementById('modal-root')\n  );\n}</code></pre>" },
        { q: "When should you use portals?", a: "<ul><li>Modals and dialogs</li><li>Tooltips and popovers</li><li>Dropdown menus that need to overflow parents</li><li>Toast notifications</li><li>Any UI that should visually break out of its container</li></ul>" },
        { q: "Do events bubble through portals?", a: "<p>Yes! Even though a portal renders in a different DOM node, events still bubble up through the React tree (not the DOM tree). A click inside a portal will bubble to parent React components.</p>" },
        { q: "Does context work with portals?", a: "<p>Yes, portals are part of the React tree, so they have access to the same context as their parent component in the React hierarchy, regardless of where they render in the DOM.</p>" },
        { q: "How do you create a modal with a portal?", a: "<pre><code>function Modal({ isOpen, onClose, children }) {\n  if (!isOpen) return null;\n  return createPortal(\n    &lt;div className=\"overlay\" onClick={onClose}&gt;\n      &lt;div className=\"modal\" onClick={e =&gt; e.stopPropagation()}&gt;\n        {children}\n        &lt;button onClick={onClose}&gt;Close&lt;/button&gt;\n      &lt;/div&gt;\n    &lt;/div&gt;,\n    document.body\n  );\n}</code></pre>" },
        { q: "How do you handle keyboard events in portal modals?", a: "<p>Add an event listener for the Escape key and manage focus trapping:</p><pre><code>useEffect(() =&gt; {\n  const handleEsc = (e) =&gt; { if (e.key === 'Escape') onClose(); };\n  document.addEventListener('keydown', handleEsc);\n  return () =&gt; document.removeEventListener('keydown', handleEsc);\n}, [onClose]);</code></pre>" },
        { q: "What DOM node should portals render into?", a: "<p>Common choices: <code>document.body</code>, a dedicated <code>&lt;div id='portal-root'&gt;</code> in index.html, or dynamically created elements. Avoid rendering into the root app div to prevent layout issues.</p>" },
        { q: "Can you nest portals?", a: "<p>Yes, you can nest portals. Each portal renders independently at its target DOM node. Events still bubble through the React tree, not the DOM tree.</p>" },
        { q: "How do portals affect accessibility?", a: "<p>Portals can break tab order and screen reader flow. You must manage focus (focus trap in modals), add aria attributes (role='dialog', aria-modal, aria-label), and return focus when the portal closes.</p>" },
        { q: "Can you use portals in server-side rendering?", a: "<p>Portals require a DOM node, so they don't work during SSR. Use conditional rendering to only mount portals on the client side with <code>useEffect</code> or check <code>typeof window !== 'undefined'</code>.</p>" }
    ]
},
{
    id: "suspense-lazy-loading", title: "Suspense & Lazy Loading", icon: "bi-hourglass-split",
    questions: [
        { q: "What is React.lazy?", a: "<p><code>React.lazy</code> enables component-level code splitting. It takes a function that returns a dynamic import:</p><pre><code>const LazyProfile = React.lazy(() =&gt; import('./Profile'));\n\nfunction App() {\n  return (\n    &lt;Suspense fallback={&lt;Loading /&gt;}&gt;\n      &lt;LazyProfile /&gt;\n    &lt;/Suspense&gt;\n  );\n}</code></pre>" },
        { q: "What is Suspense?", a: "<p>Suspense lets you show a fallback UI while waiting for lazy components or asynchronous data to load. It catches a \"suspended\" state from its children.</p>" },
        { q: "How does code splitting improve performance?", a: "<p>Code splitting breaks the bundle into smaller chunks loaded on demand. Users download only the code they need, reducing initial load time. Each lazy-loaded route or component becomes a separate chunk.</p>" },
        { q: "Can Suspense handle data fetching?", a: "<p>Yes, with React 18+ and frameworks like Next.js or Relay. The component throws a promise during render, Suspense catches it, and shows the fallback until resolved.</p>" },
        { q: "How do you lazy load routes?", a: "<pre><code>const Home = React.lazy(() =&gt; import('./pages/Home'));\nconst About = React.lazy(() =&gt; import('./pages/About'));\n\nfunction App() {\n  return (\n    &lt;Suspense fallback={&lt;Spinner /&gt;}&gt;\n      &lt;Routes&gt;\n        &lt;Route path=\"/\" element={&lt;Home /&gt;} /&gt;\n        &lt;Route path=\"/about\" element={&lt;About /&gt;} /&gt;\n      &lt;/Routes&gt;\n    &lt;/Suspense&gt;\n  );\n}</code></pre>" },
        { q: "What is the startTransition API?", a: "<p><code>startTransition</code> marks updates as non-urgent, letting React keep the UI responsive during expensive re-renders:</p><pre><code>import { startTransition } from 'react';\n\nstartTransition(() =&gt; {\n  setSearchResults(filteredData); // Non-urgent update\n});</code></pre>" },
        { q: "What is useTransition?", a: "<pre><code>const [isPending, startTransition] = useTransition();\n\nconst handleChange = (e) =&gt; {\n  setInput(e.target.value); // Urgent\n  startTransition(() =&gt; {\n    setFilteredList(filter(e.target.value)); // Non-urgent\n  });\n};\n\nreturn isPending ? &lt;Spinner /&gt; : &lt;List items={filteredList} /&gt;;</code></pre>" },
        { q: "Can you nest Suspense boundaries?", a: "<p>Yes! Each Suspense boundary catches suspensions independently. Inner Suspense shows its own fallback while the outer shows for other components:</p><pre><code>&lt;Suspense fallback={&lt;PageSkeleton /&gt;}&gt;\n  &lt;Header /&gt;\n  &lt;Suspense fallback={&lt;PostSkeleton /&gt;}&gt;\n    &lt;Posts /&gt;\n  &lt;/Suspense&gt;\n&lt;/Suspense&gt;</code></pre>" },
        { q: "What are loading and error states with Suspense?", a: "<p>Suspense handles loading states. For errors, wrap with an error boundary:</p><pre><code>&lt;ErrorBoundary fallback={&lt;Error /&gt;}&gt;\n  &lt;Suspense fallback={&lt;Loading /&gt;}&gt;\n    &lt;DataComponent /&gt;\n  &lt;/Suspense&gt;\n&lt;/ErrorBoundary&gt;</code></pre>" },
        { q: "Does React.lazy support named exports?", a: "<p>React.lazy only supports default exports. For named exports, create an intermediate module:</p><pre><code>// MathUtils.js exports { Calculator }\n\n// Calculator.js (wrapper)\nexport { Calculator as default } from './MathUtils';\n\nconst Calculator = React.lazy(() =&gt; import('./Calculator'));</code></pre>" }
    ]
},
{
    id: "virtual-dom", title: "Virtual DOM & Reconciliation", icon: "bi-tree",
    questions: [
        { q: "What is the Virtual DOM?", a: "<p>The Virtual DOM is a lightweight JavaScript representation of the real DOM. React creates a virtual tree, and when state changes, it creates a new virtual tree, diffs the two, and applies only the minimum necessary changes to the real DOM. This is faster than directly manipulating the DOM for complex UIs.</p>" },
        { q: "How does reconciliation work?", a: "<p>Reconciliation is React's algorithm for diffing two virtual DOM trees. It uses two heuristics: elements of different types produce different trees (full remount), and developers provide <code>key</code> props to identify stable elements across renders.</p>" },
        { q: "What is React Fiber?", a: "<p>Fiber is React's reconciliation engine (React 16+). It breaks rendering work into incremental units, allowing React to pause, resume, and prioritize updates. This enables features like Suspense, concurrent rendering, and time-slicing.</p>" },
        { q: "Why are keys important in lists?", a: "<p>Keys help React identify which items changed, were added, or removed. Without keys, React re-renders all items. With stable keys, it efficiently reorders, adds, or removes individual items:</p><pre><code>items.map(item =&gt; &lt;li key={item.id}&gt;{item.name}&lt;/li&gt;)</code></pre><p>Never use array index as key if the list can reorder.</p>" },
        { q: "What happens when element types differ?", a: "<p>When React encounters different element types at the same position, it tears down the entire old subtree and builds a new one. For example, changing from <code>&lt;div&gt;</code> to <code>&lt;span&gt;</code> unmounts the div and all its children.</p>" },
        { q: "What is batching in React?", a: "<p>React 18 automatically batches all state updates, even inside promises, setTimeout, and event handlers. Multiple setState calls in one event are batched into a single re-render for performance.</p>" },
        { q: "What is concurrent rendering?", a: "<p>Concurrent rendering (React 18+) lets React prepare multiple versions of the UI simultaneously, interrupt rendering for higher-priority updates, and keep the UI responsive during expensive computations.</p>" },
        { q: "How does React handle component updates?", a: "<p>When a component re-renders, React: 1) Calls the component function to get new JSX, 2) Diffs new virtual DOM with previous, 3) Computes minimal DOM changes, 4) Commits changes to the real DOM. Child components re-render if parent re-renders (unless memoized).</p>" },
        { q: "What is the difference between virtual DOM and shadow DOM?", a: "<p><strong>Virtual DOM:</strong> React concept — a JS representation of the DOM for diffing. <strong>Shadow DOM:</strong> Browser API for scoped CSS and DOM encapsulation in Web Components. They are unrelated technologies solving different problems.</p>" },
        { q: "How does React optimize list rendering?", a: "<p>React uses the key prop to match old and new elements. With keys, it can: reorder elements efficiently, preserve component state during reorder, add/remove specific items without re-rendering the entire list. Always use unique, stable IDs as keys.</p>" }
    ]
},
{
    id: "event-handling", title: "Event Handling", icon: "bi-mouse",
    questions: [
        { q: "How does event handling work in React?", a: "<p>React uses synthetic events — cross-browser wrappers around native events. Events are named using camelCase and passed as functions:</p><pre><code>function Button() {\n  const handleClick = (e) =&gt; {\n    e.preventDefault();\n    console.log('Clicked!');\n  };\n  return &lt;button onClick={handleClick}&gt;Click Me&lt;/button&gt;;\n}</code></pre>" },
        { q: "What are synthetic events?", a: "<p>Synthetic events are React's cross-browser wrapper objects that conform to the W3C spec. They have the same interface as native events (stopPropagation(), preventDefault()) but work identically across browsers. They are pooled for performance.</p>" },
        { q: "How do you pass arguments to event handlers?", a: "<pre><code>// Arrow function (creates new function each render)\n&lt;button onClick={() =&gt; handleDelete(item.id)}&gt;Delete&lt;/button&gt;\n\n// Using data attributes\n&lt;button data-id={item.id} onClick={handleDelete}&gt;Delete&lt;/button&gt;\nconst handleDelete = (e) =&gt; {\n  const id = e.currentTarget.dataset.id;\n};</code></pre>" },
        { q: "What is event delegation in React?", a: "<p>React uses event delegation by default — it attaches a single event listener to the root DOM container rather than to individual elements. When an event fires, React determines which component it belongs to using its internal mapping. This is more memory-efficient.</p>" },
        { q: "How do you prevent default behavior?", a: "<p>Call <code>e.preventDefault()</code> on the synthetic event:</p><pre><code>function Form() {\n  const handleSubmit = (e) =&gt; {\n    e.preventDefault();\n    // Handle form data\n  };\n  return &lt;form onSubmit={handleSubmit}&gt;...&lt;/form&gt;;\n}</code></pre>" },
        { q: "How do you handle keyboard events?", a: "<pre><code>function SearchInput() {\n  const handleKeyDown = (e) =&gt; {\n    if (e.key === 'Enter') {\n      performSearch();\n    }\n    if (e.key === 'Escape') {\n      clearInput();\n    }\n  };\n  return &lt;input onKeyDown={handleKeyDown} /&gt;;\n}</code></pre>" },
        { q: "What is the difference between onChange and onInput?", a: "<p>In React, <code>onChange</code> fires on every change (mimics the native <code>input</code> event). In native HTML, <code>onchange</code> only fires on blur. React's onChange is the preferred way to handle input changes.</p>" },
        { q: "How do you handle events in lists efficiently?", a: "<p>Instead of attaching handlers to each item, use event delegation on the parent:</p><pre><code>function List({ items, onDelete }) {\n  const handleClick = (e) =&gt; {\n    const id = e.target.closest('[data-id]')?.dataset.id;\n    if (id) onDelete(id);\n  };\n  return (\n    &lt;ul onClick={handleClick}&gt;\n      {items.map(item =&gt; (\n        &lt;li key={item.id} data-id={item.id}&gt;{item.name} &lt;button&gt;X&lt;/button&gt;&lt;/li&gt;\n      ))}\n    &lt;/ul&gt;\n  );\n}</code></pre>" },
        { q: "How do you handle window or document events?", a: "<pre><code>useEffect(() =&gt; {\n  const handleScroll = () =&gt; setScrollY(window.scrollY);\n  window.addEventListener('scroll', handleScroll);\n  return () =&gt; window.removeEventListener('scroll', handleScroll);\n}, []);</code></pre>" },
        { q: "What is stopPropagation in React?", a: "<p><code>e.stopPropagation()</code> prevents the event from bubbling up to parent elements in both the React tree and the DOM. Useful when nested clickable elements should not trigger parent handlers.</p>" }
    ]
},
{
    id: "performance-optimization", title: "Performance Optimization", icon: "bi-speedometer2",
    questions: [
        { q: "What is React.memo?", a: "<p><code>React.memo</code> is a higher-order component that memoizes the result. It only re-renders if props change (shallow comparison):</p><pre><code>const ExpensiveList = React.memo(function List({ items }) {\n  return items.map(item =&gt; &lt;li key={item.id}&gt;{item.name}&lt;/li&gt;);\n});</code></pre>" },
        { q: "What is useMemo?", a: "<p><code>useMemo</code> memoizes expensive computations:</p><pre><code>const sortedItems = useMemo(() =&gt; {\n  return items.sort((a, b) =&gt; a.name.localeCompare(b.name));\n}, [items]);</code></pre><p>Only recalculates when <code>items</code> changes.</p>" },
        { q: "What is useCallback?", a: "<p><code>useCallback</code> memoizes function references to prevent unnecessary re-renders of child components:</p><pre><code>const handleDelete = useCallback((id) =&gt; {\n  setItems(prev =&gt; prev.filter(item =&gt; item.id !== id));\n}, []);</code></pre>" },
        { q: "When should you NOT memoize?", a: "<ul><li>Simple, fast computations (memoization has overhead)</li><li>Values that change on every render anyway</li><li>Components that are cheap to render</li><li>When it makes code harder to read for minimal gain</li></ul><p>Profile first, optimize second.</p>" },
        { q: "How do you profile React performance?", a: "<p>Use React DevTools Profiler to record renders and identify slow components. Also use <code>React.Profiler</code> component in code:</p><pre><code>&lt;Profiler id=\"sidebar\" onRender={(id, phase, actualDuration) =&gt; {\n  console.log(id, phase, actualDuration);\n}}&gt;\n  &lt;Sidebar /&gt;\n&lt;/Profiler&gt;</code></pre>" },
        { q: "What causes unnecessary re-renders?", a: "<ul><li>Parent re-renders (all children re-render)</li><li>Creating new objects/arrays in render (breaks shallow comparison)</li><li>Inline function definitions as props</li><li>Context value changes (all consumers re-render)</li><li>State updates that don't change the value</li></ul>" },
        { q: "How do you optimize context to avoid re-renders?", a: "<p>Split context by update frequency, memoize the value object, or use state management libraries:</p><pre><code>const value = useMemo(() =&gt; ({\n  user, theme\n}), [user, theme]);\n\nreturn &lt;AppContext.Provider value={value}&gt;...&lt;/AppContext.Provider&gt;;</code></pre>" },
        { q: "What is windowing/virtualization?", a: "<p>Render only visible items in large lists using libraries like <code>react-window</code> or <code>react-virtuoso</code>:</p><pre><code>import { FixedSizeList } from 'react-window';\n\n&lt;FixedSizeList height={400} itemCount={10000} itemSize={35}&gt;\n  {({ index, style }) =&gt; (\n    &lt;div style={style}&gt;Row {index}&lt;/div&gt;\n  )}\n&lt;/FixedSizeList&gt;</code></pre>" },
        { q: "How do you optimize images in React?", a: "<p>Use lazy loading, responsive images, next-gen formats (WebP), and proper sizing:</p><pre><code>&lt;img\n  src=\"photo.webp\"\n  loading=\"lazy\"\n  width={400}\n  height={300}\n  alt=\"Description\"\n/&gt;</code></pre>" },
        { q: "What is code splitting best practices?", a: "<p>Split at: route level (most common), component level (heavy components), library level (import only what you need). Use dynamic <code>import()</code>, React.lazy, and analyze bundle with source-map-explorer.</p>" }
    ]
},
{
    id: "testing", title: "Testing", icon: "bi-bug",
    questions: [
        { q: "How do you test a React component?", a: "<pre><code>import { render, screen } from '@testing-library/react';\n\ntest('renders greeting', () =&gt; {\n  render(&lt;Hello name=\"World\" /&gt;);\n  expect(screen.getByText('Hello, World!')).toBeInTheDocument();\n});</code></pre>" },
        { q: "What is React Testing Library philosophy?", a: "<p>Test components the way users interact with them. Query by accessible roles, text, and labels — not by class names or implementation details. If it's not visible to users, don't test it.</p>" },
        { q: "How do you test user interactions?", a: "<pre><code>import { render, screen } from '@testing-library/react';\nimport userEvent from '@testing-library/user-event';\n\ntest('increments counter', async () =&gt; {\n  render(&lt;Counter /&gt;);\n  await userEvent.click(screen.getByRole('button', { name: /increment/i }));\n  expect(screen.getByText('Count: 1')).toBeInTheDocument();\n});</code></pre>" },
        { q: "How do you test async operations?", a: "<pre><code>test('loads user data', async () =&gt; {\n  render(&lt;UserProfile id=\"1\" /&gt;);\n  expect(screen.getByText('Loading...')).toBeInTheDocument();\n  await screen.findByText('John Doe'); // Waits for element\n  expect(screen.queryByText('Loading...')).not.toBeInTheDocument();\n});</code></pre>" },
        { q: "How do you mock API calls in tests?", a: "<pre><code>import { rest } from 'msw';\nimport { setupServer } from 'msw/node';\n\nconst server = setupServer(\n  rest.get('/api/users', (req, res, ctx) =&gt; {\n    return res(ctx.json([{ id: 1, name: 'John' }]));\n  })\n);\n\nbeforeAll(() =&gt; server.listen());\nafterEach(() =&gt; server.resetHandlers());\nafterAll(() =&gt; server.close());</code></pre>" },
        { q: "How do you test custom hooks?", a: "<pre><code>import { renderHook, act } from '@testing-library/react';\n\ntest('useCounter hook', () =&gt; {\n  const { result } = renderHook(() =&gt; useCounter());\n  expect(result.current.count).toBe(0);\n  act(() =&gt; result.current.increment());\n  expect(result.current.count).toBe(1);\n});</code></pre>" },
        { q: "How do you test components with context?", a: "<pre><code>function renderWithProviders(ui) {\n  return render(\n    &lt;ThemeProvider&gt;\n      &lt;AuthProvider&gt;\n        {ui}\n      &lt;/AuthProvider&gt;\n    &lt;/ThemeProvider&gt;\n  );\n}\n\ntest('shows user name', () =&gt; {\n  renderWithProviders(&lt;UserInfo /&gt;);\n  expect(screen.getByText('John')).toBeInTheDocument();\n});</code></pre>" },
        { q: "What are common Testing Library queries?", a: "<ul><li><code>getByRole</code> — by ARIA role (preferred)</li><li><code>getByText</code> — by visible text</li><li><code>getByLabelText</code> — by form label</li><li><code>getByPlaceholderText</code> — by placeholder</li><li><code>getByTestId</code> — by data-testid (last resort)</li><li><code>queryBy*</code> — returns null if not found</li><li><code>findBy*</code> — async, waits for element</li></ul>" },
        { q: "How do you test form submission?", a: "<pre><code>test('submits form data', async () =&gt; {\n  const onSubmit = jest.fn();\n  render(&lt;LoginForm onSubmit={onSubmit} /&gt;);\n  await userEvent.type(screen.getByLabelText('Email'), 'test@example.com');\n  await userEvent.type(screen.getByLabelText('Password'), 'secret');\n  await userEvent.click(screen.getByRole('button', { name: /submit/i }));\n  expect(onSubmit).toHaveBeenCalledWith({ email: 'test@example.com', password: 'secret' });\n});</code></pre>" },
        { q: "What is snapshot testing?", a: "<p>Snapshot testing captures rendered component output and compares it to a stored reference:</p><pre><code>test('matches snapshot', () =&gt; {\n  const { asFragment } = render(&lt;Button label=\"Click\" /&gt;);\n  expect(asFragment()).toMatchSnapshot();\n});</code></pre><p>Use sparingly — snapshots break easily and provide less insight than specific assertions.</p>" }
    ]
},
{
    id: "server-components-ssr", title: "Server Components & SSR", icon: "bi-server",
    questions: [
        { q: "What is Server-Side Rendering (SSR)?", a: "<p>SSR renders React components to HTML on the server and sends the fully rendered page to the browser. Benefits: faster first paint, better SEO, works without JavaScript. The browser then hydrates the HTML with React to make it interactive.</p>" },
        { q: "What are React Server Components (RSC)?", a: "<p>RSC (React 18+) are components that run exclusively on the server. They can directly access databases, file systems, and backend services. They send rendered HTML to the client — no JavaScript bundle for these components.</p>" },
        { q: "What is hydration?", a: "<p>Hydration is the process where React attaches event handlers and state to server-rendered HTML, making it interactive. React reuses the existing DOM rather than replacing it.</p>" },
        { q: "What is the difference between SSR and SSG?", a: "<p><strong>SSR (Server-Side Rendering):</strong> HTML generated on each request. Best for dynamic content. <strong>SSG (Static Site Generation):</strong> HTML generated at build time. Best for content that doesn't change frequently. SSG is faster since pages are pre-built.</p>" },
        { q: "What is streaming SSR?", a: "<p>Streaming SSR (React 18) sends HTML to the browser in chunks as components render, instead of waiting for the entire page. Combined with Suspense, fast parts appear immediately while slow parts load.</p>" },
        { q: "What is the 'use client' directive?", a: "<p>In React Server Components architecture, <code>'use client'</code> marks a component as a Client Component that runs in the browser:</p><pre><code>'use client';\n\nimport { useState } from 'react';\n\nexport function Counter() {\n  const [count, setCount] = useState(0);\n  return &lt;button onClick={() =&gt; setCount(c + 1)}&gt;{count}&lt;/button&gt;;\n}</code></pre>" },
        { q: "What is the 'use server' directive?", a: "<p><code>'use server'</code> marks a function as a Server Action that can be called from the client:</p><pre><code>'use server';\n\nexport async function saveUser(formData) {\n  const name = formData.get('name');\n  await db.users.create({ name });\n}</code></pre>" },
        { q: "What is ISR (Incremental Static Regeneration)?", a: "<p>ISR (Next.js feature) regenerates static pages in the background after a specified time interval. Pages are served statically but updated periodically without full rebuild.</p>" },
        { q: "What can Server Components NOT do?", a: "<ul><li>Use hooks (useState, useEffect, etc.)</li><li>Add event handlers (onClick, onChange)</li><li>Use browser APIs (window, document)</li><li>Maintain client-side state</li></ul><p>For interactivity, use Client Components with 'use client'.</p>" },
        { q: "How does Next.js implement RSC?", a: "<p>In Next.js App Router, all components are Server Components by default. Add <code>'use client'</code> at the top of files that need interactivity. Server Components can import Client Components but not vice versa. Data fetching happens directly in Server Components with async/await.</p>" }
    ]
}
];

// Read and extend
var content = fs.readFileSync(filePath, 'utf8');
var lastBracket = content.lastIndexOf(']');
var before = content.substring(0, lastBracket);
var after = content.substring(lastBracket);

var topicsStr = topics.map(t => {
    var qs = t.questions.map(q => '            { q: ' + JSON.stringify(q.q) + ', a: ' + JSON.stringify(q.a) + ' }').join(',\n');
    return '        {\n            id: ' + JSON.stringify(t.id) + ', title: ' + JSON.stringify(t.title) + ', icon: ' + JSON.stringify(t.icon) + ',\n            questions: [\n' + qs + '\n            ]\n        }';
}).join(',\n');

fs.writeFileSync(filePath, before + ',\n' + topicsStr + '\n' + after, 'utf8');
console.log('Extended react-data.js with 10 more topics');
